Movies10/Models/Pelicula.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Movies10.Models
{
    public class Pelicula
    {
        //PhotoID. This is the primary key
        [Key]
        public int PeliID { get; set; }
        //Title. The title of the photo
        [Required]
        [StringLength(200)]
        public string Title { get; set; }
        //Title. The title of the photo
        [DisplayName("Poster")]
        [MaxLength]
        public byte[] Poster { get; set; }
        //ImageMimeType, stores the MIME type for the PhotoFile
        [HiddenInput(DisplayValue = false)]
        public string ImageMimeType { get; set; }
        //Description.
        [DataType(DataType.MultilineText)]
        public string Sinopsis { get; set; }
        //CreatedDate
        [DataType(DataType.DateTime)]
        [DisplayName("Created Date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yy}", ApplyFormatInEditMode = true)]
        public DateTime Fecha_estreno { get; set; }
        //UserName. This is the name of the user who created the photo
        [Required]
        public string Director { get; set; }
        public virtual ICollection<Comentario> Comentarios { get; set; }
    }
}

Movies10/Controllers/PeliculasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Movies.Models;
using Movies10.Models;

namespace Movies10.Controllers
{
    public class PeliculasController : Controller
    {
        private Pelidb db = new Pelidb();

        // GET: Peliculas
        public async Task<ActionResult> Index()
        {
            return View(await db.Pelicula.ToListAsync());
        }

        // GET: Peliculas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pelicula pelicula = await db.Pelicula.FindAsync(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        // GET: Peliculas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Peliculas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "PeliID,Title,Poster,ImageMimeType,Sinopsis,Fecha_estreno,Director")] Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                db.Pelicula.Add(pelicula);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(pelicula);
        }

        // GET: Peliculas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pelicula pelicula = await db.Pelicula.FindAsync(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        // POST: Peliculas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PeliID,Title,Poster,ImageMimeType,Sinopsis,Fecha_estreno,Director")] Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pelicula).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(pelicula);
        }

        // GET: Peliculas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pelicula pelicula = await db.Pelicula.FindAsync(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        // POST: Peliculas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Pelicula pelicula = await db.Pelicula.FindAsync(id);
            db.Pelicula.Remove(pelicula);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        ///// otros
        public ActionResult Create2()
        {
            Pelicula newPeli = new Pelicula();
            newPeli.Fecha_estreno = DateTime.Today;

            return View("Create", newPeli);
        }

        [HttpPost]
        public ActionResult Create2(Pelicula pelicula, HttpPostedFileBase image)
        {
            pelicula.Fecha_estreno = DateTime.Today;

            if (!ModelState.IsValid)
            {
                return View("Create", pelicula);
            }
            else
            {
                if (image != null)
                {
                    pelicula.ImageMimeType = image.ContentType;
                    pelicula.Poster = new byte[image.ContentLength];
                    image.InputStream.Read(pelicula.Poster, 0, image.ContentLength);
                }

                db.Pelicula.Add(pelicula);
                db.SaveChanges();
                return RedirectToAction("Index");

            }
        }





        public FileContentResult GetImage(int id)
        {
            Pelicula pelicula = db.Pelicula.Find(id);
               

            if (pelicula != null)
            {
                return File(pelicula.Poster, pelicula.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

Movies10/Controllers/PhotoController.cs
using Movies.Models;
using Movies10.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Movies10.Controllers
{
    [ValueReporter]
    public class PhotoController : Controller
    {
        private Pelidb context = new Pelidb();

        // GET: Photo
        public ActionResult Index()
        {
            return View("Index");
        }

        [ChildActionOnly]
        public ActionResult _PhotoGallery(int number = 0)
        {
            List<Pelicula> pelicula;
            if (number == 0)
            {
                pelicula = context.Pelicula.ToList();
            }
            else
            {
                pelicula = (from p in context.Pelicula orderby p.Fecha_estreno descending select p).Take(number).ToList();
            }

            return PartialView("_PhotoGallery", pelicula);
        }

        public ActionResult Display(int id)
        {
            Pelicula pelicula = context.Pelicula.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }

            return View("Display", pelicula);
        }

        public ActionResult Create()
        {
            Pelicula newpelicula = new Pelicula();
            newpelicula.Fecha_estreno = DateTime.Today;

            return View("Create", newpelicula);
        }

        [HttpPost]
        public ActionResult Create(Pelicula pelicula, HttpPostedFileBase image)
        {
            pelicula.Fecha_estreno = DateTime.Today;

            if (!ModelState.IsValid)
            {
                return View("Create", pelicula);
            }
            else
            {
                if (image != null)
                {
                    pelicula.ImageMimeType = image.ContentType;
                    pelicula.Poster = new byte[image.ContentLength];
                    image.InputStream.Read(pelicula.Poster, 0, image.ContentLength);
                }

                context.Pelicula.Add(pelicula);
                context.SaveChanges();
                return RedirectToAction("Index");

            }
        }

        public ActionResult Delete(int id)
        {
            Pelicula pelicula = context.Pelicula.Find(id);

            if (pelicula == null)
            {
                return HttpNotFound();
            }

            return View("Delete", pelicula);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Pelicula pelicula = context.Pelicula.Find(id);

            context.Pelicula.Remove(pelicula);
            context.SaveChanges();
            return RedirectToAction("Index");

        }

        public FileContentResult GetImage(int id)
        {
            Pelicula photo = context.Pelicula.Find(id);

            if (photo != null)
            {
                return File(photo.Poster, photo.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

Movies10/Views/Peliculas/Create.cshtml
@model Movies10.Models.Pelicula

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pelicula</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Poster, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Poster, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Poster, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageMimeType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageMimeType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageMimeType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sinopsis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sinopsis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sinopsis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_estreno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha_estreno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha_estreno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Movies10/Views/Peliculas/Delete.cshtml
@model Movies10.Models.Pelicula

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pelicula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Poster)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Poster)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageMimeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageMimeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sinopsis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sinopsis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha_estreno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha_estreno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Director)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Director)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Movies10/Views/Peliculas/Details.cshtml
@model Movies10.Models.Pelicula

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Pelicula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Poster)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Poster)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageMimeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageMimeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sinopsis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sinopsis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha_estreno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha_estreno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Director)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Director)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PeliID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Movies10/Views/Peliculas/Edit.cshtml
@model Movies10.Models.Pelicula

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pelicula</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PeliID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Poster, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Poster, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Poster, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageMimeType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageMimeType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageMimeType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sinopsis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sinopsis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sinopsis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_estreno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha_estreno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha_estreno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Movies10/Views/Peliculas/Index.cshtml
@model IEnumerable<Movies10.Models.Pelicula>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    @Html.ActionLink("Create New", "Create2","Photo")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Poster)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageMimeType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sinopsis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha_estreno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Director)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Poster)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImageMimeType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sinopsis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha_estreno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Director)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PeliID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PeliID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PeliID })
        </td>
    </tr>
}

</table>